package fr.arindam.aws.dynamodb.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@ToString
@AllArgsConstructor
@NoArgsConstructor
@Data
@DynamoDBTable(tableName = "company")
public class Company {
	
	@DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
	private String id;
	
	
	/**
	 * This is a sort key
	 */
    @DynamoDBRangeKey
	private String company_name;
    
    @DynamoDBAttribute
    private String description;
}
